import { PositionNewTypeTextEnum } from "../../enums/position";

export const ColorPositionDefines: Record<string, string> = {
  [PositionNewTypeTextEnum.DATA_SCIENTIST]: '#7d7d7d',
  [PositionNewTypeTextEnum.SOFTWARE_ENGINEER]: '#112a73',
  [PositionNewTypeTextEnum.CLOUD_ENGINEER]: '#7d47b2',
  [PositionNewTypeTextEnum.UX_DESIGNER]: '#2b98de',
  [PositionNewTypeTextEnum.FRONTEND_DEVELOPER]: '#00bca3',
  [PositionNewTypeTextEnum.PRODUCT_MANAGER]: '#065700',
  [PositionNewTypeTextEnum.SYSTEMS_ANALYST]: '#9b3016',
  [PositionNewTypeTextEnum.CYBERSECURITY_SPECIALIST]: '#f98c79',
  [PositionNewTypeTextEnum.DATABASE_ADMINISTRATOR]: '#facd02',
  [PositionNewTypeTextEnum.SECURITY_ENGINEER]: '#34383c',
  [PositionNewTypeTextEnum.DATA_ENGINEER]: '#394d6c',
  [PositionNewTypeTextEnum.CLOUD_ARCHITECT]: '#9987ff',
  [PositionNewTypeTextEnum.PRODUCT_DESIGNER]: '#084d73',
  [PositionNewTypeTextEnum.DEVOPS_ENGINEER]: '#016b5d',
  [PositionNewTypeTextEnum.BACKEND_ENGINEER]: '#b7d1ad',
  [PositionNewTypeTextEnum.CYBERSECURITY_ANALYST]: '#e37829',
  [PositionNewTypeTextEnum.MARKETING_MANAGER]: '#8c3c4b',
  [PositionNewTypeTextEnum.TECHNICAL_LEAD]: '#cd8b02',
  [PositionNewTypeTextEnum.AI_ENGINEER]: '#e4e2de',
  [PositionNewTypeTextEnum.FULL_STACK_DEVELOPER]: '#a3b8de',
  [PositionNewTypeTextEnum.MACHINE_LEARNING_ENGINEER]: '#f3c2f8',
  [PositionNewTypeTextEnum.IT_PROJECT_MANAGER]: '#8ac3f4',
  [PositionNewTypeTextEnum.NETWORK_ENGINEER]: '#b5e7e2',
  [PositionNewTypeTextEnum.SOFTWARE_ARCHITECT]: '#789c30',
  [PositionNewTypeTextEnum.UI_UX_DESIGNERE]: '#c46531',
  [PositionNewTypeTextEnum.MARKETING_SPECIALIST]: '#f7bfb5',
  [PositionNewTypeTextEnum.BUSINESS_ANALYST]: '#c4b08f',
  [PositionNewTypeTextEnum.SALES_ENGINEER]: '#25a7ff',
  [PositionNewTypeTextEnum.FRONTEND_ENGINEER]: '#00bca3',
}