/**
 * @description 定義 Position Type Code 類型
 */
export enum PositionTypeCodeEnum {
  ALL = 1,
  SOFTWARE_ENGINEER = 2,
  DESIGNER = 3,
  PM = 4,
  MARKETING = 5,
  FINANCE = 6,
  OTHER = 7
}

// export enum PositionNewTypeCodeEnum {
//   ALL = 1,
//   DATA_SCIENTIST = 2,
//   SOFTWARE_ENGINEER = 3,
//   CLOUD_ENGINEER = 4,
//   UX_DESIGNER = 5,
//   FRONTEND_DEVELOPER = 6,
//   PRODUCT_MANAGER = 7,
//   SYSTEMS_ANALYST = 8,
//   CYBERSECURITY_SPECIALIST = 9,
//   DATABASE_ADMINISTRATOR = 10,
//   SECURITY_ENGINEER = 11,
//   DATA_ENGINEER = 12,
//   CLOUD_ARCHITECT = 13,
//   PRODUCT_DESIGNER = 14,
//   DEVOPS_ENGINEER = 15,
//   BACKEND_ENGINEER = 16,
//   CYBERSECURITY_ANALYST = 17,
//   MARKETING_MANAGER = 18,
//   TECHNICAL_LEAD = 19,
//   AI_ENGINEER = 20,
//   FULL_STACK_DEVELOPER = 21,
//   MACHINE_LEARNING_ENGINEER = 22,
//   IT_PROJECT_MANAGER = 23,
//   NETWORK_ENGINEER = 24,
//   SOFTWARE_ARCHITECT = 25,
//   UI_UX_DESIGNERE = 26,
//   MARKETING_SPECIALIST = 27,
//   BUSINESS_ANALYST = 28,
//   SALES_ENGINEER = 29,
//   FRONTEND_ENGINEER = 30
// }